apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-awx-postgres-0
spec:
  storageClassName: my-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
